name: Docker Build and Run Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build -t openeo_insar . -f OpenEO_Dockerfile

      - name: Run OpenEO_insar_preprocessing
        run: |
          docker run --rm \
            -v $(pwd):/src \
            -w /src \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            openeo_insar pip install -e ".[dev]" && python -m pytest
